name: LearnJava

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Gửi thông báo đến Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"content": "```Phát hiện Pull Request, đang tìm kiếm selfhost rảnh rỗi! ```"}' \
        https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R

  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Thông Báo khởi động sv
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"content": "```Lưu ý server đang khởi động, không được call api cho tới khi có thông báo mới!```"}' https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
  
    - name: Build with Maven
      run: mvn clean install
  
    - name: List files in target directory
      run: ls target
  
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
  
    - name: Hello world
      run: |
        touch .env
        echo DOCKER_HUB_ACCESS_TOKEN=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} >> .env
        echo DOCKER_HUB_ACCESS_USER=${{ secrets.DOCKER_HUB_ACCESS_USER }} >> .env
        echo MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} >> .env
        echo MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} >> .env
  
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_ACCESS_USER }}" --password-stdin
        
    - name: Build and Push DockerFile
      run: |
        docker-compose -f docker-compose.yaml build
        docker-compose -f docker-compose.yaml push
  
    - name: Stop and remove containers
      run: docker-compose -f docker-compose.yaml down
  
  deploy:
    environment:
      name: Java-Api
      url: 103.205.60.174:8080
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS
        run: |
          sudo apt-get install -y sshpass
          
          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
          cd server/
          docker compose down
          docker rmi lmao1415/dath_cnpm
          # Tạo mới hoặc kết nối tới một phiên tmux
          tmux kill-session -t mysession 2>/dev/null || true &&
          tmux new-session -d -s mysession 'docker compose up'
          "
      
      - name: Chờ 1 phút trước khi gửi thông báo
        run: |
          sleep 60
          
      - name: Thông Báo khởi động sv
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "```Server đã khởi động thành công!```"}' https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R
