name: LearnJava

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create .env file
        run: |
          touch .env
          echo "DOCKER_HUB_ACCESS_TOKEN=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" >> .env 
          echo "DOCKER_HUB_ACCESS_USER=${{ secrets.DOCKER_HUB_ACCESS_USER }}" >> .env 
          echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" >> .env 
          echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> .env 

      - name: docker compose
        run: |
          docker compose up
