name: LearnJava

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - docs/**
      # - .github/workflows/**

jobs:
  notify:
    runs-on: self-hosted

    steps:
    - name: Gửi thông báo đến Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"content": "```Phát hiện Pull Request trên nhánh main, đang tìm kiếm selfhost rảnh rỗi! ```"}' \
        https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R

  build:
    environment: dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
  
    - name: Thông Báo khởi động sv
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"content": "```Lưu ý server đang khởi động, không được call api cho tới khi có thông báo mới!```"}' https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
  
    - name: Build with Maven
      run: mvn clean install
        
    - name: Build and Push DockerFile
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_ACCESS_USER }}" --password-stdin
        sudo docker build -t lmao1415/dath_cnpm .
        sudo docker push lmao1415/dath_cnpm
  
    - name: Remove Docker Image
      run: sudo docker rmi lmao1415/dath_cnpm
  
  deploy:
    environment:
      name: dev
      url: nope
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to VPS
        env:
          VPS_USER: root
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }} 
        run: |
          sudo apt-get install -y sshpass
          
          sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "
          cd server/
          
          echo 'y' | sudo docker container prune
          sudo docker rmi $(docker images -a -q) 2>dev>null || true  
          sudo docker compose down
          sudo docker compose pull
          
          # Tạo mới hoặc kết nối tới một phiên tmux
          tmux kill-session -t spring 2>/dev/null || true &&
          tmux new-session -d -s spring 'sudo docker compose up'
          "
          
      - name: Thông Báo khởi động sv
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "```Server đã khởi động thành công!```"}' https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R
