name: Production change

on:
  push:
    branches:
      - Production

jobs:
  notify:
    runs-on: self-hosted

    steps:
      # - name: Gửi thông báo đến Discord
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" \
      #     -d '{"content": "@everyone```Phát hiện Pull Request, trên nhánh Production! ```"}' \
      #     https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R

      - name: In danh sách file
        run: |
          ls -a

  deploy:
    environment: production
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to VPS
        run: |
          rm -rf server 2>/dev/null || true
          sudo docker rmi $(docker images -a -q) 2>dev>null || true
        
          git clone --branch Production https://github.com/dath-241/coin-price-be-java.git server
          cd server
          
          touch .env
          
          echo 'MONGO_DB_URI=${{secrets.MONGO_DB_URI}}' >> .env
          echo 'MONGO_DB_NAME=${{secrets.MONGO_DB_NAME}}' >> .env
          echo 'JWT_SECRET=${secrets.JWT_SECRET}}' >> .env
          
          echo 'TELEGRAM_WEBHOOK_URL=${{secrets.TELEGRAM_WEBHOOK_URL}}' >> .env
          echo 'TELEGRAM_BOT_TOKEN=${{secrets.TELEGRAM_BOT_TOKEN}}' >> .env
          echo 'TELEGRAM_CHAT_ID=${{secrets.TELEGRAM_CHAT_ID}}' >> .env
          
          echo 'email=${{email}' >> .env
          echo 'password_for_email=${{secrets.password_for_email}}' >> .env
          
          echo 'adminToken=${{secrets.adminToken}}' >> .env

          sudo docker compose down

          tmux kill-session -t mysession 2>/dev/null || true &&
          tmux new-session -d -s mysession 'sudo docker compose up'
          
      # - name: Thông Báo khởi động sv
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" -d '{"content": "```Server đã khởi động thành công!```"}' https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R
