name: Production change

on:
  push:
    branches: 
      - Production

jobs:
  notify:
    runs-on: self-hosted

    steps:
    # - name: Gửi thông báo đến Discord
    #   run: |
    #     curl -X POST -H "Content-Type: application/json" \
    #     -d '{"content": "@everyone```Phát hiện Pull Request, đang tìm kiếm selfhost rảnh rỗi! ```"}' \
    #     https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R

    - name: In danh sách file
      run: |
        ls -a

  deploy:
      environment:
        name: dev
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      runs-on: self-hosted
      steps:
        - name: Deploy to VPS
          env:
            VPS_USER: root
            VPS_IP: ${{ secrets.VPS_IP }}
            VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }} 
          run: |
            sudo apt-get install -y sshpass
            
            sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "
            git clone --branch Production https://github.com/dath-241/coin-price-be-java.git server
            cd server
            
            # ========================= Thông tin nhạy cảm =============================
            touch .env

            echo 'MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}' >> .env
            echo 'MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}' >> .env
            echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> .env
            
            echo 'TELEGRAM_WEBHOOK_URL=${{ secrets.TELEGRAM_WEBHOOK_URL }}' >> .env
            echo 'TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}' >> .env
            echo 'TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}' >> .env
            
            echo 'email=${{ secrets.email }}' >> .env
            echo 'password_for_email=${{ secrets.password_for_email }}' >> .env
            
            echo 'adminToken=${{ secrets.adminToken }}' >> .env
            # =======================================================
            
            sudo docker compose down
            sudo docker rmi lmao1415/dath_cnpm
            # Tạo mới hoặc kết nối tới một phiên tmux
            tmux kill-session -t mysession 2>/dev/null || true &&
            tmux new-session -d -s mysession 'sudo docker compose up'
            "
            
        - name: Thông Báo khởi động sv
          run: |
            curl -X POST -H "Content-Type: application/json" -d '{"content": "```Server đã khởi động thành công!```"}' https://discord.com/api/webhooks/1297132713119191121/B72OrNxwgv1-l5svlDvzUzIWLhtnlmnb4xoPH9BqoX6vG655uPK-vKirbAvmGIjHgt3R
